# Generated by Django 3.2.3 on 2021-08-03 02:24

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='learn-default-profile-pic.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[myapp.models.enforce_rating]),
        ),
    ]
