# Generated by Django 3.2.3 on 2021-08-05 22:10

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210802_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(upload_to=myapp.models.user_directory_path),
        ),
    ]
