# Generated by Django 3.2.3 on 2021-08-06 05:06

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, upload_to=myapp.models.user_directory_path),
        ),
    ]
